version: '3.8'

services:
  springboot-app:
    container_name: "springboot-app"
    build: .
    ports:
      - "3009:3009"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/db_school?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysql-container

  mysql-container:
    container_name: "mysql-container"
    image: "mysql:8.0"
    ports:
      - "5800:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "db_school"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
